import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"; 
import { DarkModeProvider } from "./context/DarkModeContext";
import Header from "./components/Header";
import Footer from "./components/Footer";
 
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap", // Improves perceived loading performance
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "vSave - einfach sparen",
  description: "Generated by MC",
  viewport: {
    width: "device-width",
    initialScale: 1,
    maximumScale: 5,
    userScalable: true,
  },
  themeColor: "#ffffff",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="flex flex-col">
        <DarkModeProvider>
          <Header />
          <main className="flex-grow w-full px-4 py-5 md:container md:mx-auto md:p-6">{children}</main>
          <Footer />
        </DarkModeProvider>
      </body>
    </html>
  );
}