import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css"; 
import { DarkModeProvider } from "./context/DarkModeContext";
import Header from "./components/Header";
import Footer from "./components/Footer";
 
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="min-h-screen flex flex-col">
        <DarkModeProvider>
          <Header />
          <main className="flex-grow container mx-auto p-6">{children}</main>
          <Footer />
        </DarkModeProvider>
      </body>
    </html>
  );
}